In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
df1= pd.read_csv('.\csvs\Internetfijoportecnologiaylocalidad.csv')

In [3]:
df1.head(10)

,Provincia,Partido,Localidad,Link Indec,ADSL,CABLEMODEM,DIAL UP,FIBRA OPTICA,OTROS,SATELITAL,WIMAX,WIRELESS,Total general,Unnamed: 13
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,874,"4,54",- 0,3,- 0,852,- 0,706,"6,98",NaN
1,BUENOS AIRES,25 de Mayo,Del Valle,6854020,181,- 0,- 0,- 0,10,1,- 0,- 0,192,NaN
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,- 0,- 0,- 0,- 0,- 0,- 0,- 0,181,181,NaN
3,BUENOS AIRES,25 de Mayo,Norberto de la Riestra,6854060,- 0,782,- 0,6,167,- 0,- 0,327,"1,28",NaN
4,BUENOS AIRES,25 de Mayo,Lucas Monteverde,6854050,- 0,- 0,- 0,- 0,- 0,- 0,- 0,6,6,NaN
5,BUENOS AIRES,25 de Mayo,Ernestina,6854030,66,- 0,- 0,- 0,- 0,- 0,- 0,- 0,66,NaN
6,BUENOS AIRES,25 de Mayo,Pedernales,6854070,568,- 0,- 0,- 0,- 0,- 0,- 0,7,575,NaN
7,BUENOS AIRES,9 de Julio,12 de Octubre,6588030,- 0,- 0,- 0,- 0,- 0,- 0,- 0,19,19,NaN
8,BUENOS AIRES,9 de Julio,9 de Julio,6588100,"4,31","3,35",82,"6,23",83,1,- 0,831,"14,89",NaN
9,BUENOS AIRES,9 de Julio,Alfredo Demarchi (Est. Facundo Quiroga),6588010,450,- 0,- 0,- 0,60,- 0,- 0,- 0,510,NaN

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3137 entries, 0 to 3136
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Provincia      3137 non-null   object
 1   Partido        3137 non-null   object
 2   Localidad      3137 non-null   object
 3   Link Indec     3137 non-null   object
 4   ADSL           3137 non-null   object
 5   CABLEMODEM     3137 non-null   object
 6   DIAL UP        3137 non-null   object
 7   FIBRA OPTICA   3137 non-null   object
 8   OTROS          3137 non-null   object
 9   SATELITAL      3137 non-null   object
 10  WIMAX          3137 non-null   object
 11  WIRELESS       3137 non-null   object
 12  Total general  3137 non-null   object
 13  Unnamed: 13    0 non-null      float64
dtypes: float64(1), object(13)
memory usage: 343.2+ KB

In [5]:
def data_inspeccion(variables):
    print(f'Shape: {variables.shape}')
    print(f'\nDatos faltantes:')
    for columna in variables.columns:
        cantidad_nulos = variables[columna].isnull().sum()
        print(f'{columna}: {cantidad_nulos} valores nulos')

data_inspeccion(df1)

Shape: (3137, 14)

Datos faltantes:
Provincia: 0 valores nulos
Partido: 0 valores nulos
Localidad: 0 valores nulos
Link Indec: 0 valores nulos
ADSL: 0 valores nulos
CABLEMODEM: 0 valores nulos
DIAL UP: 0 valores nulos
FIBRA OPTICA: 0 valores nulos
OTROS: 0 valores nulos
SATELITAL: 0 valores nulos
WIMAX: 0 valores nulos
WIRELESS: 0 valores nulos
Total general: 0 valores nulos
Unnamed: 13: 3137 valores nulos

In [6]:
# Eliminare las filas con valores nulos 
df1.dropna(inplace=True)

# Visualizó
data_inspeccion(df1)

Shape: (0, 14)

Datos faltantes:
Provincia: 0 valores nulos
Partido: 0 valores nulos
Localidad: 0 valores nulos
Link Indec: 0 valores nulos
ADSL: 0 valores nulos
CABLEMODEM: 0 valores nulos
DIAL UP: 0 valores nulos
FIBRA OPTICA: 0 valores nulos
OTROS: 0 valores nulos
SATELITAL: 0 valores nulos
WIMAX: 0 valores nulos
WIRELESS: 0 valores nulos
Total general: 0 valores nulos
Unnamed: 13: 0 valores nulos

lectura del segundo dataframe

In [7]:
df2= pd.read_csv('.\csvs\Internetfijoporvelocidadbajadayprovincia.csv')

In [8]:
df2.head()

,Año,Trimestre,Provincia,Otros,"0,256 Mbps","0,375 Mbps","0,625 Mbps","0,5 Mbps","0,512 Mbps","0,75 Mbps",...,63 Mbps,64 Mbps,65 Mbps,66 Mbps,67 Mbps,68 Mbps,70 Mbps,71 Mbps,75 Mbps,77 Mbps
0,2022.0,4.0,Buenos Aires,97.634,18,- 0,- 0,28.724,192,4.611,...,- 0,- 0,14,- 0,- 0,- 0,5.655,- 0,90.796,- 0
1,2022.0,4.0,Capital Federal,106.772,31,- 0,- 0,451.000,34,1.307,...,- 0,- 0,- 0,1,- 0,- 0,15,- 0,28.406,- 0
2,2022.0,4.0,Catamarca,2.280,- 0,- 0,- 0,34.000,37,- 0,...,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0
3,2022.0,4.0,Chaco,3.909,- 0,225,111,234.000,2,- 0,...,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0
4,2022.0,4.0,Chubut,20.026,8,- 0,- 0,69.000,32,836,...,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0,- 0

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 97 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Año         504 non-null    float64
 1   Trimestre   504 non-null    float64
 2   Provincia   504 non-null    object
 3   Otros       504 non-null    object
 4   0,256 Mbps  504 non-null    object
 5   0,375 Mbps  504 non-null    object
 6   0,625 Mbps  504 non-null    object
 7   0,5 Mbps    504 non-null    float64
 8   0,512 Mbps  504 non-null    object
 9   0,75 Mbps   504 non-null    object
 10  1 Mbps      504 non-null    object
 11  1,2 Mbps    504 non-null    object
 12  1,25 Mbps   504 non-null    object
 13  1,5 Mbps    504 non-null    object
 14  2 Mbps      504 non-null    object
 15  2,2 Mbps    504 non-null    object
 16  2,5 Mbps    505 non-null    object
 17  6,7 Mbps    504 non-null    object
 18  3 Mbps      504 non-null    float64
 19  3,2 Mbps    504 non-null    object
 20  3,3 Mbps    504 non-null    object
 21  3,5 Mbps    504 non-null    object
 22  4 Mbps      504 non-null    object
 23  4,5 Mbps    504 non-null    object
 24  5 Mbps      504 non-null    object
 25  6 Mbps      504 non-null    object
 26  6,4 Mbps    504 non-null    object
 27  7 Mbps      504 non-null    object
 28  7,5 Mbps    504 non-null    object
 29  8 Mbps      504 non-null    object
 30  9 Mbps      504 non-null    object
 31  10 Mbps     504 non-null    float64
 32  10,2 Mbps   504 non-null    object
 33  10,6 Mbps   504 non-null    object
 34  11 Mbps     504 non-null    object
 35  12 Mbps     504 non-null    object
 36  12,3 Mbps   504 non-null    object
 37  13 Mbps     504 non-null    object
 38  14 Mbps     504 non-null    object
 39  15 Mbps     504 non-null    object
 40  16 Mbps     504 non-null    object
 41  17 Mbps     504 non-null    object
 42  18 Mbps     504 non-null    object
 43  19 Mbps     504 non-null    object
 44  20 Mbps     504 non-null    object
 45  20,5 Mbps   504 non-null    object
 46  21 Mbps     504 non-null    object
 47  22 Mbps     504 non-null    object
 48  23 Mbps     504 non-null    object
 49  24 Mbps     504 non-null    object
 50  25 Mbps     504 non-null    object
 51  25,1 Mbps   504 non-null    object
 52  25,11 Mbps  504 non-null    object
 53  25,5 Mbps   504 non-null    object
 54  26 Mbps     504 non-null    object
 55  27 Mbps     504 non-null    object
 56  28 Mbps     504 non-null    object
 57  29 Mbps     504 non-null    object
 58  30 Mbps     504 non-null    object
 59  31 Mbps     504 non-null    object
 60  32 Mbps     504 non-null    object
 61  34 Mbps     504 non-null    object
 62  35 Mbps     504 non-null    object
 63  36 Mbps     504 non-null    object
 64  37 Mbps     504 non-null    object
 65  38 Mbps     504 non-null    object
 66  39 Mbps     504 non-null    object
 67  40 Mbps     504 non-null    object
 68  41 Mbps     504 non-null    object
 69  45 Mbps     504 non-null    object
 70  46 Mbps     504 non-null    object
 71  47 Mbps     504 non-null    object
 72  48 Mbps     504 non-null    object
 73  49 Mbps     504 non-null    object
 74  50 Mbps     504 non-null    object
 75  50,1 Mbps   504 non-null    object
 76  51 Mbps     504 non-null    object
 77  50,25 Mbps  504 non-null    object
 78  52 Mbps     504 non-null    object
 79  54 Mbps     504 non-null    object
 80  55 Mbps     504 non-null    object
 81  56 Mbps     504 non-null    object
 82  58 Mbps     504 non-null    object
 83  59 Mbps     504 non-null    object
 84  60 Mbps     504 non-null    object
 85  61 Mbps     504 non-null    object
 86  62 Mbps     504 non-null    object
 87  63 Mbps     504 non-null    object
 88  64 Mbps     504 non-null    object
 89  65 Mbps     504 non-null    object
 90  66 Mbps     504 non-null    object
 91  67 Mbps     504 non-null    object
 92  68 Mbps     504 non-null    object
 93  70 Mbps     504 non-null    object
 94  71 Mbps     504 non-null    object
 95  75 Mbps     504 non-null    object
 96  77 Mbps     504 non-null    object
dtypes: float64(5), object(92)
memory usage: 382.8+ KB

In [10]:
def data_inspeccion(variables):
    print(f'Shape: {variables.shape}')
    print(f'\nDatos faltantes:')
    for columna in variables.columns:
        cantidad_nulos = variables[columna].isnull().sum()
        print(f'{columna}: {cantidad_nulos} valores nulos')

data_inspeccion(df2)

Shape: (505, 97)

Datos faltantes:
Año: 1 valores nulos
Trimestre: 1 valores nulos
Provincia: 1 valores nulos
Otros: 1 valores nulos
0,256 Mbps: 1 valores nulos
0,375 Mbps: 1 valores nulos
0,625 Mbps: 1 valores nulos
0,5 Mbps: 1 valores nulos
0,512 Mbps: 1 valores nulos
0,75 Mbps: 1 valores nulos
1 Mbps: 1 valores nulos
1,2 Mbps: 1 valores nulos
1,25 Mbps: 1 valores nulos
1,5 Mbps: 1 valores nulos
2 Mbps: 1 valores nulos
2,2 Mbps: 1 valores nulos
2,5 Mbps: 0 valores nulos
6,7 Mbps: 1 valores nulos
3 Mbps: 1 valores nulos
3,2 Mbps: 1 valores nulos
3,3 Mbps: 1 valores nulos
3,5 Mbps: 1 valores nulos
4 Mbps: 1 valores nulos
4,5 Mbps: 1 valores nulos
5 Mbps: 1 valores nulos
6 Mbps: 1 valores nulos
6,4 Mbps: 1 valores nulos
7 Mbps: 1 valores nulos
7,5 Mbps: 1 valores nulos
8 Mbps: 1 valores nulos
9 Mbps: 1 valores nulos
10 Mbps: 1 valores nulos
10,2 Mbps: 1 valores nulos
10,6 Mbps: 1 valores nulos
11 Mbps: 1 valores nulos
12 Mbps: 1 valores nulos
12,3 Mbps: 1 valores nulos
13 Mbps: 1 valores nulos
14 Mbps: 1 valores nulos
15 Mbps: 1 valores nulos
16 Mbps: 1 valores nulos
17 Mbps: 1 valores nulos
18 Mbps: 1 valores nulos
19 Mbps: 1 valores nulos
20 Mbps: 1 valores nulos
20,5 Mbps: 1 valores nulos
21 Mbps: 1 valores nulos
22 Mbps: 1 valores nulos
23 Mbps: 1 valores nulos
24 Mbps: 1 valores nulos
25 Mbps: 1 valores nulos
25,1 Mbps: 1 valores nulos
25,11 Mbps: 1 valores nulos
25,5 Mbps: 1 valores nulos
26 Mbps: 1 valores nulos
27 Mbps: 1 valores nulos
28 Mbps: 1 valores nulos
29 Mbps: 1 valores nulos
30 Mbps: 1 valores nulos
31 Mbps: 1 valores nulos
32 Mbps: 1 valores nulos
34 Mbps: 1 valores nulos
35 Mbps: 1 valores nulos
36 Mbps: 1 valores nulos
37 Mbps: 1 valores nulos
38 Mbps: 1 valores nulos
39 Mbps: 1 valores nulos
40 Mbps: 1 valores nulos
41 Mbps: 1 valores nulos
45 Mbps: 1 valores nulos
46 Mbps: 1 valores nulos
47 Mbps: 1 valores nulos
48 Mbps: 1 valores nulos
49 Mbps: 1 valores nulos
50 Mbps: 1 valores nulos
50,1 Mbps: 1 valores nulos
51 Mbps: 1 valores nulos
50,25 Mbps: 1 valores nulos
52 Mbps: 1 valores nulos
54 Mbps: 1 valores nulos
55 Mbps: 1 valores nulos
56 Mbps: 1 valores nulos
58 Mbps: 1 valores nulos
59 Mbps: 1 valores nulos
60 Mbps: 1 valores nulos
61 Mbps: 1 valores nulos
62 Mbps: 1 valores nulos
63 Mbps: 1 valores nulos
64 Mbps: 1 valores nulos
65 Mbps: 1 valores nulos
66 Mbps: 1 valores nulos
67 Mbps: 1 valores nulos
68 Mbps: 1 valores nulos
70 Mbps: 1 valores nulos
71 Mbps: 1 valores nulos
75 Mbps: 1 valores nulos
77 Mbps: 1 valores nulos

In [11]:
# Eliminare las filas con valores nulos 
df2.dropna(inplace=True)

# Visualizó
data_inspeccion(df2)

Shape: (504, 97)

Datos faltantes:
Año: 0 valores nulos
Trimestre: 0 valores nulos
Provincia: 0 valores nulos
Otros: 0 valores nulos
0,256 Mbps: 0 valores nulos
0,375 Mbps: 0 valores nulos
0,625 Mbps: 0 valores nulos
0,5 Mbps: 0 valores nulos
0,512 Mbps: 0 valores nulos
0,75 Mbps: 0 valores nulos
1 Mbps: 0 valores nulos
1,2 Mbps: 0 valores nulos
1,25 Mbps: 0 valores nulos
1,5 Mbps: 0 valores nulos
2 Mbps: 0 valores nulos
2,2 Mbps: 0 valores nulos
2,5 Mbps: 0 valores nulos
6,7 Mbps: 0 valores nulos
3 Mbps: 0 valores nulos
3,2 Mbps: 0 valores nulos
3,3 Mbps: 0 valores nulos
3,5 Mbps: 0 valores nulos
4 Mbps: 0 valores nulos
4,5 Mbps: 0 valores nulos
5 Mbps: 0 valores nulos
6 Mbps: 0 valores nulos
6,4 Mbps: 0 valores nulos
7 Mbps: 0 valores nulos
7,5 Mbps: 0 valores nulos
8 Mbps: 0 valores nulos
9 Mbps: 0 valores nulos
10 Mbps: 0 valores nulos
10,2 Mbps: 0 valores nulos
10,6 Mbps: 0 valores nulos
11 Mbps: 0 valores nulos
12 Mbps: 0 valores nulos
12,3 Mbps: 0 valores nulos
13 Mbps: 0 valores nulos
14 Mbps: 0 valores nulos
15 Mbps: 0 valores nulos
16 Mbps: 0 valores nulos
17 Mbps: 0 valores nulos
18 Mbps: 0 valores nulos
19 Mbps: 0 valores nulos
20 Mbps: 0 valores nulos
20,5 Mbps: 0 valores nulos
21 Mbps: 0 valores nulos
22 Mbps: 0 valores nulos
23 Mbps: 0 valores nulos
24 Mbps: 0 valores nulos
25 Mbps: 0 valores nulos
25,1 Mbps: 0 valores nulos
25,11 Mbps: 0 valores nulos
25,5 Mbps: 0 valores nulos
26 Mbps: 0 valores nulos
27 Mbps: 0 valores nulos
28 Mbps: 0 valores nulos
29 Mbps: 0 valores nulos
30 Mbps: 0 valores nulos
31 Mbps: 0 valores nulos
32 Mbps: 0 valores nulos
34 Mbps: 0 valores nulos
35 Mbps: 0 valores nulos
36 Mbps: 0 valores nulos
37 Mbps: 0 valores nulos
38 Mbps: 0 valores nulos
39 Mbps: 0 valores nulos
40 Mbps: 0 valores nulos
41 Mbps: 0 valores nulos
45 Mbps: 0 valores nulos
46 Mbps: 0 valores nulos
47 Mbps: 0 valores nulos
48 Mbps: 0 valores nulos
49 Mbps: 0 valores nulos
50 Mbps: 0 valores nulos
50,1 Mbps: 0 valores nulos
51 Mbps: 0 valores nulos
50,25 Mbps: 0 valores nulos
52 Mbps: 0 valores nulos
54 Mbps: 0 valores nulos
55 Mbps: 0 valores nulos
56 Mbps: 0 valores nulos
58 Mbps: 0 valores nulos
59 Mbps: 0 valores nulos
60 Mbps: 0 valores nulos
61 Mbps: 0 valores nulos
62 Mbps: 0 valores nulos
63 Mbps: 0 valores nulos
64 Mbps: 0 valores nulos
65 Mbps: 0 valores nulos
66 Mbps: 0 valores nulos
67 Mbps: 0 valores nulos
68 Mbps: 0 valores nulos
70 Mbps: 0 valores nulos
71 Mbps: 0 valores nulos
75 Mbps: 0 valores nulos
77 Mbps: 0 valores nulos

In [12]:
df2.describe()

               Año   Trimestre      0,5 Mbps        3 Mbps        10 Mbps
count   504.000000  504.000000    504.000000    504.000000     504.000000
mean   2019.857143    2.571429    135.160514    536.427409    1830.656857
std       1.522341    1.138019   1281.313402   3423.594162   13716.783075
min    2017.000000    1.000000      1.009000      1.029000       1.000000
25%    2019.000000    2.000000     19.000000      5.910000       7.161500
50%    2020.000000    3.000000     39.000000      9.833000      20.563500
75%    2021.000000    4.000000     69.000000     27.000000      92.386750
max    2022.000000    4.000000  28724.000000  53034.000000  204191.000000